import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Login(),
        ]),
      ),
    );
  }
}

class Login extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1920,
          height: 1080,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(
            color: const Color(0xFFEADDFF) /* Schemes-Primary-Container */,
          ),
          child: Stack(
            children: [
              Positioned(
                left: 720,
                top: 298.50,
                child: ConstrainedBox(
                  constraints: BoxConstraints(minWidth: 480),
                  child: Container(
                    padding: const EdgeInsets.all(24),
                    decoration: ShapeDecoration(
                      color: Colors.white /* Schemes-On-Primary */,
                      shape: RoundedRectangleBorder(
                        side: BorderSide(
                          width: 1,
                          color: const Color(0xFFD9D9D9) /* Border-Default-Default */,
                        ),
                        borderRadius: BorderRadius.circular(8),
                      ),
                    ),
                    child: Column(
                      mainAxisSize: MainAxisSize.min,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      spacing: 24,
                      children: [
                        Container(
                          width: double.infinity,
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            spacing: 12,
                            children: [
                              SizedBox(
                                width: 408,
                                child: Text(
                                  'Email',
                                  style: TextStyle(
                                    color: const Color(0xFF1E1E1E) /* Text-Default-Default */,
                                    fontSize: 16,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 1.40,
                                  ),
                                ),
                              ),
                              ConstrainedBox(
                                constraints: BoxConstraints(minWidth: 360),
                                child: Container(
                                  width: double.infinity,
                                  padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 18),
                                  clipBehavior: Clip.antiAlias,
                                  decoration: ShapeDecoration(
                                    color: Colors.white /* Background-Default-Default */,
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1.50,
                                        strokeAlign: BorderSide.strokeAlignCenter,
                                        color: const Color(0xFFD9D9D9) /* Border-Default-Default */,
                                      ),
                                      borderRadius: BorderRadius.circular(8),
                                    ),
                                  ),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      SizedBox(
                                        width: 360,
                                        child: Text(
                                          'Value',
                                          style: TextStyle(
                                            color: const Color(0xFFB3B3B3) /* Text-Default-Tertiary */,
                                            fontSize: 16,
                                            fontFamily: 'Inter',
                                            fontWeight: FontWeight.w400,
                                            height: 1,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                        Container(
                          width: double.infinity,
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            spacing: 12,
                            children: [
                              SizedBox(
                                width: 408,
                                child: Text(
                                  'Password',
                                  style: TextStyle(
                                    color: const Color(0xFF1E1E1E) /* Text-Default-Default */,
                                    fontSize: 16,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 1.40,
                                  ),
                                ),
                              ),
                              ConstrainedBox(
                                constraints: BoxConstraints(minWidth: 360),
                                child: Container(
                                  width: double.infinity,
                                  padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 18),
                                  clipBehavior: Clip.antiAlias,
                                  decoration: ShapeDecoration(
                                    color: Colors.white /* Background-Default-Default */,
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1.50,
                                        strokeAlign: BorderSide.strokeAlignCenter,
                                        color: const Color(0xFFD9D9D9) /* Border-Default-Default */,
                                      ),
                                      borderRadius: BorderRadius.circular(8),
                                    ),
                                  ),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      SizedBox(
                                        width: 360,
                                        child: Text(
                                          'Value',
                                          style: TextStyle(
                                            color: const Color(0xFFB3B3B3) /* Text-Default-Tertiary */,
                                            fontSize: 16,
                                            fontFamily: 'Inter',
                                            fontWeight: FontWeight.w400,
                                            height: 1,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                        Container(
                          width: double.infinity,
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 24,
                            children: [
                              Expanded(
                                child: Container(
                                  padding: const EdgeInsets.all(18),
                                  clipBehavior: Clip.antiAlias,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFF65558F) /* Schemes-Primary */,
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1.50,
                                        color: const Color(0xFF2C2C2C) /* Border-Brand-Default */,
                                      ),
                                      borderRadius: BorderRadius.circular(8),
                                    ),
                                  ),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    spacing: 12,
                                    children: [
                                      Text(
                                        'Sign In',
                                        style: TextStyle(
                                          color: const Color(0xFFF5F5F5) /* Text-Brand-On-Brand */,
                                          fontSize: 16,
                                          fontFamily: 'Inter',
                                          fontWeight: FontWeight.w400,
                                          height: 1,
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                        Container(
                          width: double.infinity,
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(
                                'Sign Up',
                                style: TextStyle(
                                  color: const Color(0xFF1E1E1E) /* Text-Default-Default */,
                                  fontSize: 16,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w400,
                                  decoration: TextDecoration.underline,
                                  height: 1.40,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 75,
                child: SizedBox(
                  width: 1920,
                  height: 194,
                  child: Text(
                    'Pomodoro Task Manager',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF65558F) /* Schemes-Primary */,
                      fontSize: 100,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w800,
                      height: 0.20,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}